# Generated by Django 3.2.13 on 2022-06-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Ім’я')),
                ('phone_number', models.CharField(default='None', verbose_name='Номер телефону')),
                ('notice', models.TextField(default='Empty', verbose_name='Повідомлення')),
                ('data', models.DateTimeField(verbose_name='Дата повідомлення')),
            ],
        ),
    ]
